sample_sheet: sample_sheet.yaml
protein_db: /mnt/db/amr_annotation_db/refseq_plasmids/all_plasmid.nonredundant_proteins.fasta

# Number of threads
threads:
  circlator: 2
  pgap: 16
  prokka: 12
mem_mb:
  circlator: 500
  pgap: 32000
  prokka: 1000